### ISSUE TITLE
Error: 'extracted_answer'

### ISSUE THREAD

**Issue by yuecao0119** [princeton-nlp/CharXiv#10]
Thank you very much to the author for such excellent work.
But when I was testing InternVL2, I encountered several errors after inference: 'extracted.answer'. Excuse me, is this a normal phenomenon?

**Comment by zwcolin** [comment]
Thanks for your interest! If possible, could you provide the traceback to the error? At what stage of evaluation (i.e., response generation, grading) did this error occur?

**Comment by yuecao0119** [comment]
evaluate.sh

**Comment by zwcolin** [comment]
Could you provide more details?

**Comment by JieFeng-cse** [comment]
The same issue happens with Qwen2.5. 
Looks like this
'Error: 'extracted_answer'
 62%|█████████████████████████████████████████████████████████████████████████████████▉                                                 | 625/1000 [05:46<02:47,  2.24it/s]Error: 'extracted_answer'
Error: 'extracted_answer'
Error: 'extracted_answer'
Error: 'extracted_answer'
Error: 'extracted_answer'
Error: 'extracted_answer'
Error: 'extracted_answer'
Error: 'extracted_answer'
Error: 'extracted_answer'
Error: 'extracted_answer'
Failed to get response for prompt: 
You will be given a question, an ground truth answer and a model response. You need to extract the final answer from the model response, compare it with the ground truth answer, and then assign a binary score. Avoid providing explanations in your response. If there is no provided model response, please leave the extracted answer empty and give a score of 0. 

Your response must follow json formats with keys [extract_answer, score] where the value of the score is an interger in [0, 1]. You must follow the scoring rules:

    ### Rules ###
    * If there are predefined options in the question:
        * Give a score of 1 if the final answer matches the ground truth answer exactly.
        * Give a score of 0 if the final answer does not match the ground truth answer.
    * If there are no predefined options in the question:
        * Give a score of 1 if the final answer shares the same semantic meaning with the ground truth answer (e.g., "increasing then decreasing" and "moving up then down"; "converge" and "move closer together").
        * Give a score of 0 if the final answer shares different semantic meanings from the ground truth answer (e.g., "increasing then decreasing" and "remain constant"; "converge" and "diverge").

    ### Example 1 Starts ###
    * Question: What is the trend of the red curve between t=10 and t=25?
    * Ground Truth: increasing then decreasing
    * Response: The red curve is increasing between t=10 and t=25.

    {
        "extracted_answer": "increasing",
        "score": 0
    }
    ### Example 1 Ends ###

    ### Example 2 Starts ###
    * Question: What is the interval where the blue curve achieves the maximum value among [0, 50], [50, 100], [100, 150], and [150, 200]?
    * Ground Truth: [50, 100]
    * Response: The interval where the blue curve achieves the maximum value is [50, 100].

    {
        "extracted_answer": "[50, 100]",
        "score": 1
    }
    ### Example 2 Ends ###

    ### Your Turn ###
    * Question: Compare the increment of α between β_R/8 and β_R/4, is it more, less, or equal to the increase between β_R/16 and β_R/8?
    * Ground Truth: More
    * Response: More'

**Comment by fc2869** [comment]
I also ran into this issue with Qwen2.5-VL-7B. It looks like the issue was that GPT-4 didn't follow the instruction properly and `extracted_answer` is not in the output json. You can print out the actual gpt responses (in `get_reasoning_result_gpt` in `reasoning_utils.py` for example) to see what it actually outputs. In my case when this error is raised, most of time gpt has `extract_answer` rather than `extracted _answer` in the output json.
