### ISSUE TITLE
Request: Add OpenAI's O1 models to the leaderboard

### ISSUE THREAD

**Issue by Belzedar94** [princeton-nlp/CharXiv#12]
Request in title :)

Love your work!

**Comment by zwcolin** [comment]
Thanks for the comment and we'll be rolling out o1 performance soon -- stay tuned!

**Comment by zwcolin** [comment]
o1 is at 52.60 for reasoning, falling behind sonnet 3.5 of 60.20 (current best) but above gpt4o which is 47.10. we will release the full list of its sub-scores and descriptive scores in the coming days.

**Comment by zwcolin** [comment]
o1 hits 87.45 for descriptive questions outperforming all models. The full results are shown on our website (along with a few more recent open-weight models as well): https://charxiv.github.io/
