### ISSUE TITLE
mgm inference 

### ISSUE THREAD

**Issue by ShineHop** [princeton-nlp/CharXiv#5]
Thank you for your contributions! I'm trying to inference several models, but I stuck into the problem.

I’m trying to perform inference using MGM, but I’m encountering the following error:

`Reading ./data/reasoning_val.json...
Number of test problems to run: 1000
Evaluation mode: reasoning
Output file: ./results/gen-mgm34b-reasoning_val.json
Traceback (most recent call last):
  File "/CharXiv/src/generate.py", line 51, in <module>
    generate_fn = get_generate_fn(args.model_path)
  File "/CharXiv/src/generate_lib/utils.py", line 105, in get_generate_fn
    from .mgm import generate_response
  File "/CharXiv/src/generate_lib/mgm.py", line 4, in <module>
    from mgm.model.builder import load_pretrained_model
ModuleNotFoundError: No module named 'mgm'`

To resolve this, I cloned the MGM repository and updated the paths in /src/generate_lib/mgm.py as follows:

`from mgm.model.builder import load_pretrained_model
from mgm.utils import disable_torch_init
from mgm.mm_utils import get_model_name_from_path, tokenizer_image_token, process_images
from mgm.constants import IMAGE_TOKEN_INDEX, DEFAULT_IMAGE_TOKEN, DEFAULT_IM_START_TOKEN, DEFAULT_IM_END_TOKEN
from mgm.conversation import conv_templates`

However, I’m still encountering the below error. 
`Traceback (most recent call last):
  File "/CharXiv/src/generate_lib/MGM/mgm/model/mgm_arch.py", line 169, in initialize_uni_modules
    weight_file = json.load(open(os.path.join(model_idx_path, 'model.safetensors.index.json'), 'r'))['weight_map']
FileNotFoundError: [Errno 2] No such file or directory: 'YanweiLi/MGM-34B-HD/model.safetensors.index.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/CharXiv/src/generate.py", line 56, in <module>
    generate_fn(args.model_path, queries)
  File "/CharXiv/src/generate_lib/mgm.py", line 71, in generate_response
    tokenizer, model, image_processor, context_len = load_pretrained_model(model_path, None, model_name,
  File "/CharXiv/src/generate_lib/MGM/mgm/model/builder.py", line 126, in load_pretrained_model
    model.get_model().initialize_uni_modules(model.config, for_eval=True)
  File "/CharXiv/src/generate_lib/MGM/mgm/model/mgm_arch.py", line 171, in initialize_uni_modules
    weight_file = json.load(open(os.path.join(model_idx_path, 'pytorch_model.bin.index.json'), 'r'))['weight_map']
FileNotFoundError: [Errno 2] No such file or directory: 'YanweiLi/MGM-34B-HD/pytorch_model.bin.index.json'`

How should I proceed with performing inference?

**Comment by zwcolin** [comment]
Oh sorry I didn't see the error about `FileNotFoundError: [Errno 2] No such file or directory: 'YanweiLi/MGM-34B-HD/model.safetensors.index.json'` in my previous reply.

Try updating your `transformers` package:

```
IS_NEW_TRANSFORMERS = transformers.__version__ >= "4.34.0"
```
(L37, `mgm_arch.py`)
```
if IS_NEW_TRANSFORMERS:
  try:
      weight_file = json.load(open(os.path.join(model_idx_path, 'model.safetensors.index.json'), 'r'))['weight_map']
  except:
      weight_file = json.load(open(os.path.join(model_idx_path, 'pytorch_model.bin.index.json'), 'r'))['weight_map']
else:
  weight_file = json.load(open(os.path.join(model_idx_path, 'pytorch_model.bin.index.json'), 'r'))['weight_map']
```
(L165-171,  `mgm_arch.py`)

Essentially you want to load the model with `model.safetensors.index.json` which is in their hf model repo.

**Comment by ShineHop** [comment]
Thank you for your reply! 
Actually, my transformers version is 4.36.2, and I followed your instruction, but I met another problem..
New error seems like there is a mismatch in the size (shape) of model weights during the model loading process.

`  File "/CharXiv/src/generate.py", line 56, in <module>
    generate_fn(args.model_path, queries)
  File "/CharXiv/src/generate_lib/mgm.py", line 71, in generate_response
    tokenizer, model, image_processor, context_len = load_pretrained_model(model_path, None, model_name,
  File "/CharXiv/MGM/mgm/model/builder.py", line 124, in load_pretrained_model
    model.get_model().initialize_uni_modules(model.config, for_eval=True)
  File "/CharXiv/MGM/mgm/model/mgm_arch.py", line 218, in initialize_uni_modules
    get_w(projector_weights, 'vision_tower.vision_tower', self.vision_tower, 'vision_tower')
  File "/CharXiv/MGM/mgm/model/mgm_arch.py", line 211, in get_w
    getattr(main_module, sub_module).load_state_dict(pretrain_weight)
  File "/.conda/envs/mgm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CLIPVisionModel:
        size mismatch for vision_model.embeddings.position_embedding.weight: copying a param with shape torch.Size([577, 1024]) from checkpoint, the shape in current model is torch.Size([257, 1024]).`
        
Thank you for the quick and helpful response! I would really appreciate it if you could assist me a bit more with a new error I'm encountering.

**Comment by zwcolin** [comment]
It's likely that you used the `openai/clip-vit-large-patch14` which results in (224/14)^2+1=257 tokens instead of `openai/clip-vit-large-patch14-336` which results in (336/14)^2+1=577 tokens. You should follow MGM codebase's `readme.md` to configure everything correctly before running evaluations on CharXiv. 

You should ensure that you can do the [CLI inference](https://github.com/dvlab-research/MGM/tree/main?tab=readme-ov-file#cli-inference) with the model you want to test in the MGM codebase itself as the first step. Once the model runs with any issues, you can use the same `model-path` you used in CLI inference as the `--model_path` argument in `generate.sh` of the CharXiv codebase.

**Comment by ShineHop** [comment]
I solved it! The issue was with downloading from the model_zoo on MGM. Your comments were very helpful in resolving the problem. Thanks again for the quick and detailed feedback :)
