### ISSUE TITLE
Details about MiniCPM-V2.6 (Upsize+CoT)

### ISSUE THREAD

**Issue by gujiaqivadin** [princeton-nlp/CharXiv#6]
Thanks for sharing this paper and wonderful benchmark. I am wondering the details about upsize and CoT, which shows a large peroformance boost for the every metric. The results on the benchmark are given by official benchmark or MiniCPM-V2.6 itself?

**Comment by zwcolin** [comment]
The results are provided by authors themselves. CoT refers to having a custom system prompt from what I can tell (which improves reasoning by a large margin but hurt description by a small margin). Upsize should be an optional argument that the authors added, whcih appears to have a slight boost effect on both metrics.

**Comment by zwcolin** [comment]
Since there's no follow-ups, I'll be closing this issue. If you have any further questions or issues, feel free to reopen it or create a new one. Thanks!
