### ISSUE TITLE
如何得到高清图像

### ISSUE THREAD

**Issue by yangtian6781** [princeton-nlp/CharXiv#9]
我注意到您论文里面说您重新把图像渲染成高清的jpeg图像，请问您具体是怎么做的呢？

**Comment by zwcolin** [comment]
感谢对我们工作的关注！我们自己写了矢量图(pdf, eps, etc)批量转高清位图(jpg)的脚本来处理所有arxiv源文件里的图片，但我们没有开源数据预处理这部分的代码。如果有需要的话可以直接给我们发邮件，谢谢！
